USE_CUDNN := 1        
CUDA_DIR := /usr/local/cuda
CUDA_ARCH := -gencode arch=compute_30,code=sm_30 \
             -gencode arch=compute_35,code=sm_35 \
             -gencode arch=compute_50,code=sm_50 \
             -gencode arch=compute_52,code=sm_52 \
             -gencode arch=compute_60,code=sm_60 \
             -gencode arch=compute_61,code=sm_61 \
             -gencode arch=compute_61,code=compute_61
BLAS := atlas
OPENCV_VERSION := 3
WITH_PYTHON_LAYER := 1
PYTHON_LIBRARIES := boost_python-py36 python3.6m
INCLUDE_DIRS := /usr/local/include /usr/include/python3.6 /usr/lib/python3.6/dist-packages/numpy/core/include /usr/include/hdf5/serial
LIBRARY_DIRS := /usr/lib /usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu/hdf5/serial /usr/local/cuda/targets/x86_64-linux/lib/stubs
BUILD_DIR := build
DISTRIBUTE_DIR := distribute
TEST_GPUID := 0
Q ?= @
